name: payung_pribadi_clone
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  animate_do: ^3.3.4
  cupertino_icons: ^1.0.6
  dropdown_button2: ^2.3.9
  easy_stepper: ^0.8.5+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  fpdart: ^1.1.0
  get_it: ^7.7.0
  go_router: ^14.2.7
  http: ^1.2.2
  iconify_flutter_plus: ^1.0.3
  image_picker: ^1.1.2
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/font/AvenirLTStd-Black.otf
        - asset: assets/font/AvenirLTStd-Book.otf
        - asset: assets/font/AvenirLTStd-Roman.otf
